/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzaapplication;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Mark Russell
 */
public class PizaaApplication extends javax.swing.JFrame {
    private final double PEPPERONI_PRICE = 75.0;
    private final double MUSHROOM_PRICE = 50.0;
    private final double GREEN_PEPPERS_PRICE = 35.0;
    private final double ITALIAN_SAUSAGE_PRICE = 100.0;
    private final double BLACK_OLIVES_PRICE = 62.0;
    private final double ONIONS_PRICE = 25.0;
    private final double BACON_PRICE = 125.0;
    private final double SPINACH_PRICE = 87.0;
    
    private final double MARGHERITA_PRICE = 15.0;
    private final double PEPPERONI_FLAVOR_PRICE = 18.0;
    private final double HAWAIIAN_PRICE = 20.0;
    private final double BBQ_CHICKEN_PRICE = 22.0;
    private final double VEGETARIAN_PRICE = 19.0;
    private final double MEAT_LOVERS_PRICE = 25.0;
    private final double FOUR_CHEESE_PRICE = 21.0;
    private final double SUPREME_PRICE = 23.0;
    
    private final double SMALL_PRICE = 10.0;  // Adjust according to your pricing
    private final double MEDIUM_PRICE = 15.0;
    private final double LARGE_PRICE = 20.0;

    
    private final double THIN_CRUST_PRICE = 5.0;  // Adjust according to your pricing
    private final double THICK_CRUST_PRICE = 7.0;

    private final double DINE_IN_PRICE = 2.0;  // Adjust according to your pricing
    private final double TAKE_OUT_PRICE = 0.0;
    /**
     * Creates new form PizaaApplication
     */
    public PizaaApplication() {
         initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        smallButton = new javax.swing.JRadioButton();
        mediumButton = new javax.swing.JRadioButton();
        largeButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        thin = new javax.swing.JRadioButton();
        thick = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        dineInButton = new javax.swing.JRadioButton();
        takeOutButton = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        pepperoni = new javax.swing.JCheckBox();
        mushroom = new javax.swing.JCheckBox();
        greenPeppers = new javax.swing.JCheckBox();
        ItalianSausage = new javax.swing.JCheckBox();
        bacon = new javax.swing.JCheckBox();
        spinach = new javax.swing.JCheckBox();
        BlackOlives = new javax.swing.JCheckBox();
        onions = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        margherita = new javax.swing.JCheckBox();
        supreme = new javax.swing.JCheckBox();
        bbqChicken = new javax.swing.JCheckBox();
        meatLover = new javax.swing.JCheckBox();
        fourCheese = new javax.swing.JCheckBox();
        vegetarian = new javax.swing.JCheckBox();
        hawaiian = new javax.swing.JCheckBox();
        pepperoni2 = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        order = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        cancelorder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(254, 222, 2));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));

        jPanel8.setBackground(new java.awt.Color(35, 31, 32));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 59, 67));
        jLabel1.setText("Mark Russell's Pizza House");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(254, 222, 2));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(35, 31, 32));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(254, 222, 2)), "Sizes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 1, 18), new java.awt.Color(238, 59, 67))); // NOI18N

        buttonGroup1.add(smallButton);
        smallButton.setForeground(new java.awt.Color(255, 255, 255));
        smallButton.setText("Small");
        smallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mediumButton);
        mediumButton.setForeground(new java.awt.Color(255, 255, 255));
        mediumButton.setText("Medium");

        buttonGroup1.add(largeButton);
        largeButton.setForeground(new java.awt.Color(255, 255, 255));
        largeButton.setText("Large");
        largeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("20");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("50");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("100");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(largeButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(smallButton))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(mediumButton)
                        .addGap(63, 63, 63)))
                .addGap(28, 28, 28))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallButton)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumButton)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(largeButton)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(254, 222, 2));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N

        jPanel11.setBackground(new java.awt.Color(35, 31, 32));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(254, 222, 2)), "Class Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 1, 18), new java.awt.Color(238, 59, 67))); // NOI18N

        buttonGroup3.add(thin);
        thin.setForeground(new java.awt.Color(255, 255, 255));
        thin.setText("Thin Crust");

        buttonGroup3.add(thick);
        thick.setForeground(new java.awt.Color(255, 255, 255));
        thick.setText("Thick Crust");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(thin)
                .addGap(53, 53, 53)
                .addComponent(thick)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thin)
                    .addComponent(thick))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(254, 222, 2));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(35, 31, 32));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(254, 222, 2)), "Order type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 1, 18), new java.awt.Color(238, 59, 67))); // NOI18N

        buttonGroup2.add(dineInButton);
        dineInButton.setForeground(new java.awt.Color(255, 255, 255));
        dineInButton.setText("Dine-In");

        buttonGroup2.add(takeOutButton);
        takeOutButton.setForeground(new java.awt.Color(255, 255, 255));
        takeOutButton.setText("Take-Out");
        takeOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(dineInButton)
                .addGap(63, 63, 63)
                .addComponent(takeOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dineInButton)
                    .addComponent(takeOutButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(254, 222, 2));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N

        jPanel12.setBackground(new java.awt.Color(35, 31, 32));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(254, 222, 2)), "Topppings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 1, 18), new java.awt.Color(238, 59, 67))); // NOI18N

        pepperoni.setForeground(new java.awt.Color(255, 255, 255));
        pepperoni.setText("Pepperoni");

        mushroom.setForeground(new java.awt.Color(255, 255, 255));
        mushroom.setText("Mushrooms");

        greenPeppers.setForeground(new java.awt.Color(255, 255, 255));
        greenPeppers.setText("Green Peppers");

        ItalianSausage.setForeground(new java.awt.Color(255, 255, 255));
        ItalianSausage.setText("Italian Sausage");
        ItalianSausage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalianSausageActionPerformed(evt);
            }
        });

        bacon.setForeground(new java.awt.Color(255, 255, 255));
        bacon.setText("Bacon");
        bacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconActionPerformed(evt);
            }
        });

        spinach.setForeground(new java.awt.Color(255, 255, 255));
        spinach.setText("Spinach");

        BlackOlives.setForeground(new java.awt.Color(255, 255, 255));
        BlackOlives.setText("Black Olives");

        onions.setForeground(new java.awt.Color(255, 255, 255));
        onions.setText("Onions");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("75");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("50");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("35");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("100");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("62");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("25");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("125");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("87");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mushroom)
                            .addComponent(pepperoni)
                            .addComponent(greenPeppers))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ItalianSausage)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(BlackOlives)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bacon)
                            .addComponent(spinach)
                            .addComponent(onions))
                        .addGap(39, 39, 39)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(29, 29, 29))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BlackOlives)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onions)
                            .addComponent(jLabel10))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pepperoni)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mushroom)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(greenPeppers)
                            .addComponent(jLabel7)
                            .addComponent(bacon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItalianSausage)
                            .addComponent(jLabel8)
                            .addComponent(spinach)
                            .addComponent(jLabel12))
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(254, 222, 2));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N

        jPanel14.setBackground(new java.awt.Color(35, 31, 32));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(254, 222, 2)), "Toppings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 1, 18), new java.awt.Color(238, 59, 67))); // NOI18N

        margherita.setForeground(new java.awt.Color(255, 255, 255));
        margherita.setText("Margherita");
        margherita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                margheritaActionPerformed(evt);
            }
        });

        supreme.setForeground(new java.awt.Color(255, 255, 255));
        supreme.setText("Supreme");

        bbqChicken.setForeground(new java.awt.Color(255, 255, 255));
        bbqChicken.setText("BBQ Chicken");
        bbqChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbqChickenActionPerformed(evt);
            }
        });

        meatLover.setForeground(new java.awt.Color(255, 255, 255));
        meatLover.setText("Meat Lovers");
        meatLover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatLoverActionPerformed(evt);
            }
        });

        fourCheese.setForeground(new java.awt.Color(255, 255, 255));
        fourCheese.setText("Four Cheese");
        fourCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourCheeseActionPerformed(evt);
            }
        });

        vegetarian.setForeground(new java.awt.Color(255, 255, 255));
        vegetarian.setText("Vegetarian");

        hawaiian.setForeground(new java.awt.Color(255, 255, 255));
        hawaiian.setText("Hawaiian");
        hawaiian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hawaiianActionPerformed(evt);
            }
        });

        pepperoni2.setForeground(new java.awt.Color(255, 255, 255));
        pepperoni2.setText("Pepperoni");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(margherita)
                    .addComponent(vegetarian))
                .addGap(31, 31, 31)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meatLover)
                    .addComponent(pepperoni2))
                .addGap(45, 45, 45)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hawaiian)
                    .addComponent(fourCheese))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supreme)
                    .addComponent(bbqChicken))
                .addGap(33, 33, 33))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(margherita)
                    .addComponent(hawaiian)
                    .addComponent(pepperoni2)
                    .addComponent(bbqChicken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vegetarian)
                    .addComponent(meatLover)
                    .addComponent(fourCheese)
                    .addComponent(supreme))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        order.setBackground(new java.awt.Color(255, 255, 0));
        order.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        order.setForeground(new java.awt.Color(0, 0, 0));
        order.setText("Process Order");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelorder.setBackground(new java.awt.Color(255, 255, 51));
        cancelorder.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N
        cancelorder.setForeground(new java.awt.Color(0, 0, 0));
        cancelorder.setText("Cancel Order");
        cancelorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelorderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelorder, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelorder, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void smallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallButtonActionPerformed

    private void largeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeButtonActionPerformed

    private void takeOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_takeOutButtonActionPerformed

    private void ItalianSausageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalianSausageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItalianSausageActionPerformed

    private void baconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baconActionPerformed

    private void margheritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_margheritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_margheritaActionPerformed

    private void bbqChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbqChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbqChickenActionPerformed

    private void fourCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourCheeseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourCheeseActionPerformed

    private void hawaiianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hawaiianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hawaiianActionPerformed

    private void cancelorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelorderActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup2.clearSelection();

        pepperoni.setSelected(false);
        mushroom.setSelected(false);
        greenPeppers.setSelected(false);
        ItalianSausage.setSelected(false);
        BlackOlives.setSelected(false);
        onions.setSelected(false);
        bacon.setSelected(false);
        spinach.setSelected(false);

        margherita.setSelected(false);
        pepperoni.setSelected(false);
        hawaiian.setSelected(false);
        bbqChicken.setSelected(false);
        vegetarian.setSelected(false);
        meatLover.setSelected(false);
        fourCheese.setSelected(false);
        supreme.setSelected(false);

        // Display a message dialog
        JOptionPane.showMessageDialog(this, "Order cancelled", "Order Cancelled", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cancelorderActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        // TODO add your handling code here:
         // Create a new JFrame to display order details
        JFrame orderFrame = new JFrame("Order Details");
        orderFrame.setSize(350, 700);

        // Initialize total price
        double totalPrice = 0.0;

        // Create a StringBuilder to store order details
        StringBuilder orderDetails = new StringBuilder("<html><body><h1>Order Details</h1>");
         if (smallButton.isSelected()) {
            orderDetails.append("Size: Small - Price: ").append(SMALL_PRICE).append(" pesos<br>");
            totalPrice += SMALL_PRICE;
        } else if (mediumButton.isSelected()) {
            orderDetails.append("Size: Medium - Price: ").append(MEDIUM_PRICE).append(" pesos<br>");
            totalPrice += MEDIUM_PRICE;
        } else if (largeButton.isSelected()) {
            orderDetails.append("Size: Large - Price: ").append(LARGE_PRICE).append(" pesos<br>");
            totalPrice += LARGE_PRICE;
        }
         orderDetails.append("<br>");

        // Get selected crust type and calculate price
        if (thin.isSelected()) {
            orderDetails.append("Crust: Thin - Price: ").append(THIN_CRUST_PRICE).append(" pesos<br>");
            totalPrice += THIN_CRUST_PRICE;
        } else if (thick.isSelected()) {
            orderDetails.append("Crust: Thick - Price: ").append(THICK_CRUST_PRICE).append(" pesos<br>");
            totalPrice += THICK_CRUST_PRICE;
        }
        orderDetails.append("<br>");

        // Get selected dine in or take out and calculate price
        if (dineInButton.isSelected()) {
            orderDetails.append("Dine In - Price: ").append(DINE_IN_PRICE).append(" pesos<br>");
            totalPrice += DINE_IN_PRICE;
        } else if (takeOutButton.isSelected()) {
            orderDetails.append("Take Out - Price: ").append(TAKE_OUT_PRICE).append(" pesos<br>");
            totalPrice += TAKE_OUT_PRICE;
        }
        orderDetails.append("<br>");

        // Get selected toppings and calculate price
        orderDetails.append("Toppings: ");
        totalPrice += calculateToppingsPrice(orderDetails);
        
        orderDetails.append("Flavors: ").append("<br>");
        totalPrice += calculateFlavorsPrice(orderDetails);

        // Display the total price
        orderDetails.append("Total Price: ").append(totalPrice).append(" pesos</body></html>");

        // Create a JLabel to display order details
        JLabel orderLabel = new JLabel(orderDetails.toString());
        orderLabel.setHorizontalAlignment(JLabel.CENTER);

        // Add the order label to the order frame
        orderFrame.add(orderLabel);

        // Set frame properties
        orderFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        orderFrame.setLocationRelativeTo(this);
        orderFrame.setVisible(true);
    }

    private double calculateToppingsPrice(StringBuilder orderDetails) {
        double toppingsPrice = 0.0;

        if (pepperoni.isSelected()) {
            toppingsPrice += PEPPERONI_PRICE;
            orderDetails.append("Pepperoni - Price: ").append(PEPPERONI_PRICE).append(" pesos, ").append("<br>");
        }
        if (mushroom.isSelected()) {
            toppingsPrice += MUSHROOM_PRICE;
            orderDetails.append("Mushroom - Price: ").append(MUSHROOM_PRICE).append(" pesos, ").append("<br>");
        }
        if (greenPeppers.isSelected()) {
            toppingsPrice += GREEN_PEPPERS_PRICE;
            orderDetails.append("Green Peppers - Price: ").append(GREEN_PEPPERS_PRICE).append(" pesos, ").append("<br>");
        }
        if (ItalianSausage.isSelected()) {
            toppingsPrice += ITALIAN_SAUSAGE_PRICE;
            orderDetails.append("Italian Sausage - Price: ").append(ITALIAN_SAUSAGE_PRICE).append(" pesos, ").append("<br>");
        }
        if (BlackOlives.isSelected()) {
            toppingsPrice += BLACK_OLIVES_PRICE;
            orderDetails.append("Black Olives - Price: ").append(BLACK_OLIVES_PRICE).append(" pesos, ").append("<br>");
        }
        if (onions.isSelected()) {
            toppingsPrice += ONIONS_PRICE;
            orderDetails.append("Onions - Price: ").append(ONIONS_PRICE).append(" pesos, ").append("<br>");
        }
        if (bacon.isSelected()) {
            toppingsPrice += BACON_PRICE;
            orderDetails.append("Bacon - Price: ").append(BACON_PRICE).append(" pesos, ").append("<br>");
        }
        if (spinach.isSelected()) {
            toppingsPrice += SPINACH_PRICE;
            orderDetails.append("Spinach - Price: ").append(SPINACH_PRICE).append(" pesos, ").append("<br>");
        }

        orderDetails.append("<br>");

        return toppingsPrice;
    }
    
    private double calculateFlavorsPrice(StringBuilder orderDetails) {
        
        double flavorsPrice = 0.0;
        
        // Check each flavor and add its price
        if (margherita.isSelected()) {
            flavorsPrice += MARGHERITA_PRICE;
            orderDetails.append("Margherita - Price: ").append(MARGHERITA_PRICE).append(" pesos, ").append("<br>");
        } 
        if (pepperoni.isSelected()) {
            flavorsPrice += PEPPERONI_FLAVOR_PRICE;
            orderDetails.append("Pepperoni Flavor - Price: ").append(PEPPERONI_FLAVOR_PRICE).append(" pesos, ").append("<br>");
        }
        if (hawaiian.isSelected()) {
            flavorsPrice += HAWAIIAN_PRICE;
            orderDetails.append("Hawaiian - Price: ").append(HAWAIIAN_PRICE).append(" pesos, ").append("<br>");
        }
        if (bbqChicken.isSelected()) {
            flavorsPrice += BBQ_CHICKEN_PRICE;
            orderDetails.append("BBQ Chicken - Price: ").append(BBQ_CHICKEN_PRICE).append(" pesos, ").append("<br>");
        }
        if (vegetarian.isSelected()) {
            flavorsPrice += VEGETARIAN_PRICE;
            orderDetails.append("Vegetarian - Price: ").append(VEGETARIAN_PRICE).append(" pesos, ").append("<br>");
        }
        if (meatLover.isSelected()) {
            flavorsPrice += MEAT_LOVERS_PRICE;
            orderDetails.append("Meat Lovers - Price: ").append(MEAT_LOVERS_PRICE).append(" pesos, ").append("<br>");
        }
        if (fourCheese.isSelected()) {
            flavorsPrice += FOUR_CHEESE_PRICE;
            orderDetails.append("Four Cheese - Price: ").append(FOUR_CHEESE_PRICE).append(" pesos, ").append("<br>");
        }
        if (supreme.isSelected()) {
            flavorsPrice += SUPREME_PRICE;
            orderDetails.append("Supreme - Price: ").append(SUPREME_PRICE).append(" pesos, ").append("<br>");
        }
        

   return flavorsPrice;
    }//GEN-LAST:event_orderActionPerformed

    private void meatLoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatLoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meatLoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizaaApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizaaApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizaaApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizaaApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizaaApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BlackOlives;
    private javax.swing.JCheckBox ItalianSausage;
    private javax.swing.JCheckBox bacon;
    private javax.swing.JCheckBox bbqChicken;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelorder;
    private javax.swing.JRadioButton dineInButton;
    private javax.swing.JCheckBox fourCheese;
    private javax.swing.JCheckBox greenPeppers;
    private javax.swing.JCheckBox hawaiian;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton largeButton;
    private javax.swing.JCheckBox margherita;
    private javax.swing.JCheckBox meatLover;
    private javax.swing.JRadioButton mediumButton;
    private javax.swing.JCheckBox mushroom;
    private javax.swing.JCheckBox onions;
    private javax.swing.JButton order;
    private javax.swing.JCheckBox pepperoni;
    private javax.swing.JCheckBox pepperoni2;
    private javax.swing.JRadioButton smallButton;
    private javax.swing.JCheckBox spinach;
    private javax.swing.JCheckBox supreme;
    private javax.swing.JRadioButton takeOutButton;
    private javax.swing.JRadioButton thick;
    private javax.swing.JRadioButton thin;
    private javax.swing.JCheckBox vegetarian;
    // End of variables declaration//GEN-END:variables
}
